// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCaO8QNx0MdDyv2Cg-Wj4UVRLlJayRgU',
    appId: '1:291724405113:web:63936efb25b36056aca7a8',
    messagingSenderId: '291724405113',
    projectId: 'capstone-hub-c3be8',
    authDomain: 'capstone-hub-c3be8.firebaseapp.com',
    storageBucket: 'capstone-hub-c3be8.firebasestorage.app',
    measurementId: 'G-GZWDT6TSJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHNmi75bec7Fm01MU701BZ9hIpHdOdKA',
    appId: '1:291724405113:android:4740250ed96c1b4faca7a8',
    messagingSenderId: '291724405113',
    projectId: 'capstone-hub-c3be8',
    storageBucket: 'capstone-hub-c3be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAFSmS2l3dMcREbdtssu_jd7bmSscudM',
    appId: '1:291724405113:ios:6ddea62f0f93a958aca7a8',
    messagingSenderId: '291724405113',
    projectId: 'capstone-hub-c3be8',
    storageBucket: 'capstone-hub-c3be8.firebasestorage.app',
    iosBundleId: 'com.example.craftybay.craftyBay',
  );
}
